apiVersion: v1
kind: Namespace
metadata:
  name: test1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: test1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test1-svc
  namespace: test1
  labels:
    app: test1
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1-ingress
  namespace: test1
spec:
  rules:
  - host: "test1.ldit-host.se"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test1-svc 
            port:
              number: 80
  tls:
  - hosts:
    - test1.ldit-host.se
    secretName: test1-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test1-cert
  namespace: app-test-1
spec:
  secretName: test1-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - test1.ldit-host.se
